### PR TITLE
Try to package mdlviewer

### PR DESCRIPTION
**Pull request by redstrate**

### CODE REVIEW

**Comment by NotNite** [comment]
Artifacts appear to be valid, but they don't execute citing missing KF6 dependencies:

image

**Comment by NotNite** [comment]
Great, more missing DLLs that weren't indicated until the other DLLs were added! Thanks Windows!

image

New wants are Qt6Cored, Qt6PrintSupportd, and Qt6Networkd. I had some copies on my hard drive so I tried copying them, and it also complained about Qt6Widgetsd, Qt6Xmld, KF6ItemViews, KF6IconWidgets, KF6GuiAddons, and KF6IconThemes.

**Comment by redstrate** [comment]
Right, I'm not sure why it's requiring the Debug versions of those yet - will be investigating that next

**Comment by NotNite** [comment]
FWIW the debug versions are being specified from the KDE libraries - the actual mdlviewer itself is in Release.

KF6ColorScheme:
image

novus-mdlviewer.exe:
image

**Comment by redstrate** [comment]
I had accidentally some libraries as Release then immediately told it to build as Debug, time to wipe the cache!

**Comment by redstrate** [comment]
Cool, it no longer complains about the debug dlls but I'll have to copy more DLLs that weren't picked up automatically next

**Comment by NotNite** [comment]
It's missing a zlib, and after providing one on my machine for testing, that seems to be the last blocker (everything starts without error).

**Comment by NotNite** [comment]
Scratch that, it looks like 3D rendering is busted(?)...
image

**Comment by redstrate** [comment]
I copied the zlib now, and can confirm it works (in Wine):

image

I'm not sure why the rendering is busted, that's something I can solve in front of a real Windows machine later

**Comment by redstrate** [comment]
Merging this now as the build now works, I want to improve it later with a better folder structure (Qt's default sucks, why a subfolder?)

**Comment by NotNite** [comment]
I can confirm Excel works fine. Nice work!

**Pull request merged**
